spring.application.name=velora-ai
spring.datasource.url = jdbc:mysql://localhost:3306/velora_db
spring.datasource.name = root
spring.datasource.password = root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

